FROM elasticsearch:5.6.5
 
RUN apt-get update
RUN apt-get install -y mc
 
RUN elasticsearch-plugin install http://dl.bintray.com/content/imotov/elasticsearch-plugins/org/elasticsearch/elasticsearch-analysis-morphology/5.6.5/elasticsearch-analysis-morphology-5.6.5.zip